services:
  - type: web
    name: wazobia-list
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: "app.py"
      - key: DATABASE_URL
        value: sqlite:////var/lib/render/instance/production.db
      - key: SECRET_KEY
        generateValue: true