services:
  - type: web
    name: wazobia-list
    runtime: python
    buildCommand: |
      pip install -r requirements.txt &&
    startCommand: |
      flask db stamp 40c72f2621ef &&
      flask db upgrade &&
      gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: "app.py"
      - key: DATABASE_URL
        value: postgresql://wazobia_db_xszu_user:ozIy44XO5SjuDmNw4uZdquY1GDJWUfd3@dpg-cvlfau15pdvs73dcebog-a/wazobia_db_xszu
      - key: SECRET_KEY
        generateValue: true