"""Increase password_hash column length to 256

Revision ID: 026cb370b4f8
Revises: 2316504af50b
Create Date: 2025-04-01 14:03:18.776773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026cb370b4f8'
down_revision = '2316504af50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
